#!/usr/bin/python3

# @file embed_shader.py
# @author Marceline Cramer (cramermarceline@gmail.com)
# @brief Generates a C header containing a compiled SPIR-V module.
# @date 2020-10-24
#
# @copyright Copyright (c) 2020 Marceline Cramer
#
# This file is part of Mondradiko.
#
# Mondradiko is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Mondradiko is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Mondradiko.  If not, see <https: //www.gnu.org/licenses/>.

import sys

WORDS_PER_LINE = 16

try:
    in_file_name = sys.argv[1]
except IndexError:
    print("Usage: ./compile_shader.py in_file_name.spv out_file.h")
    sys.exit(1)

out_file_name = in_file_name + ".h"
const_name = "SHADER_" + in_file_name.upper().replace('.', '_')

print("Embedding shader:", in_file_name)
print("Outputting to:   ", out_file_name)
print("Constant name:   ", const_name)

in_file = open(in_file_name, "rb")
spirv_code = in_file.read()
in_file.close()

out_file = open(out_file_name, "w")

out_file.write("// This file is automatically generated by embed_shader.py\n")
out_file.write("// @author Marceline Cramer (cramermarceline@gmail.com)\n\n")
out_file.write("const uint8_t " + const_name + "[] = {\n  ")

byte_index = 0
words_on_line = 0

while byte_index < len(spirv_code):
    byte = spirv_code[byte_index]
    byte_index += 1

    out_file.write('0x{:02x}'.format(byte))
    words_on_line += 1

    if byte_index < len(spirv_code):
        out_file.write(', ')

    if words_on_line >= WORDS_PER_LINE:
        out_file.write('\n  ')
        words_on_line = 0

out_file.write("\n};\n")

out_file.close()
